[package]
name = "optimism-elc"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rlp = { workspace = true }
prost = { workspace = true }
sha2 = { workspace = true}
async-trait = "0.1"
kzg-rs = { version = "0.2.3", default-features = false }

# derivation
optimism-derivation = { version = "0.1.0", path = "../derivation", default-features = false }
optimism-ibc-proto = { version = "0.1.0", path = "../proto", default-features = false }

# LCP
light-client = { git = "https://github.com/datachainlab/lcp", rev = "v0.2.12", default-features = false, features = ["ibc"] }

# Ethereum-IBC
ethereum-ibc = { workspace = true }
ethereum-ibc-proto = { workspace = true }

# Kona
kona-preimage = { workspace = true}
kona-proof = { workspace = true }

# Maili
maili-genesis = { workspace = true, features = ["serde"] }

# Alloy
alloy-eips = { workspace = true } # 'kzg' is unavailable in LCP because c-kzg requires std
alloy-consensus = { workspace = true}
alloy-primitives = { workspace = true }
anyhow = "1.0.95"

[dev-dependencies]
store = { git = "https://github.com/datachainlab/lcp.git", rev = "v0.2.12", default-features = false, features = ['std'] }
light-client = { git = "https://github.com/datachainlab/lcp", rev = "v0.2.12", default-features = false, features = ["ibc", "std"] }
reqwest = { version="0.12", default-features = false, features=["blocking", "json"] }