[package]
name = "optimism-elc"
version = "0.1.0"
edition = "2021"

[dependencies]
optimism-ibc-proto = { version = "0.1.0", path = "../proto", default-features = false }
hashbrown = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rlp = { workspace = true }
prost = { workspace = true }

# LC
light-client = { git = "https://github.com/datachainlab/lcp", rev = "v0.2.11", default-features = false, features = ["ibc"] }
ethereum-light-client-verifier = { git = "https://github.com/datachainlab/ethereum-light-client-rs", rev = "v0.1.4", default-features = false }

# Kona
kona-preimage = { workspace = true}

# Alloy
alloy-primitives = { workspace = true }
op-alloy-genesis = { workspace = true }
