[package]
name = "optimism-elc"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rlp = { workspace = true }
prost = { workspace = true }

# derivation
optimism-derivation = { version = "0.1.0", path = "../derivation", default-features = false }
optimism-ibc-proto = { version = "0.1.0", path = "../proto", default-features = false }

# LCP
light-client = { git = "https://github.com/datachainlab/lcp", rev = "v0.2.14", default-features = false, features = ["ibc"] }

# Ethereum-IBC
ethereum-consensus = { workspace = true }
ethereum-light-client-verifier = { workspace = true }

# Kona
kona-preimage = { workspace = true}
kona-genesis = { workspace = true}

# Alloy
alloy-consensus = { workspace = true}
alloy-primitives = { workspace = true }

[dev-dependencies]
time = { version = "0.3", default-features = false, features = ["macros", "parsing"] }
light-client = { git = "https://github.com/datachainlab/lcp", rev = "v0.2.14", default-features = false, features = ["ibc", "std"] }
store = { git = "https://github.com/datachainlab/lcp", rev = "v0.2.14", default-features = false }
