[package]
name = "optimism-elc"
version = "0.1.0"
edition = "2021"

[dependencies]
optimism-derivation = { version = "0.1.0", path = "../derivation", default-features = false }
optimism-ibc-proto = { version = "0.1.0", path = "../proto", default-features = false }
hashbrown = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rlp = { workspace = true }
prost = { workspace = true }
sha2 = { workspace = true}
async-trait = "0.1"

# LC
light-client = { git = "https://github.com/datachainlab/lcp", rev = "v0.2.11", default-features = false, features = ["ibc"] }
ethereum-ibc = { workspace = true }
ethereum-ibc-proto = { workspace = true }

# Kona
kona-preimage = { workspace = true}

# Alloy
alloy-consensus = { workspace = true}
alloy-primitives = { workspace = true }
op-alloy-genesis = { workspace = true }
