[package]
name = "optimism-ibc-proto"
version = "0.1.0"
edition = "2021"

[lib]
name = "optimism_ibc_proto"
path = "src/lib.rs"
doctest = false

[package.metadata.docs.rs]
all-features = true

[dependencies]
prost       = { workspace = true }
serde       = { workspace = true }
schemars    = { version = "0.8", optional = true }
ethereum-ibc-proto = { workspace = true }

[features]
default     = ["std"]
std         = []
json-schema = []