[package]
name = "optimism-ibc-proto"
version = "0.1.0"
edition = "2021"

[lib]
name = "optimism_ibc_proto"
path = "src/lib.rs"
doctest = false

[package.metadata.docs.rs]
all-features = true

[dependencies]
prost       = { version = "0.11", default-features = false }
serde       = { version = "1.0", default-features = false }
schemars    = { version = "0.8", optional = true }

[features]
default     = ["std"]
std         = []
json-schema = []