//! End-to-end tests for the optimism light client.
//!
//! These drive the full `update_client` / misbehaviour flow against
//! prover-generated fixtures in `../testdata/*.bin`. They are `#[ignore]`d
//! because they require regenerated testdata; run with
//! `cargo test -- --ignored` after regeneration.

use std::collections::BTreeMap;
use std::str::FromStr;

use light_client::types::{Any, ClientId, Height, Time};
use light_client::{ClientReader, HostClientReader, HostContext, LightClient, UpdateClientResult};
use optimism_elc::client::OptimismLightClient;
use optimism_elc::client_state::ClientState;
use optimism_elc::consensus_state::ConsensusState;
use optimism_elc::preset::minimal::PRESET;
use optimism_ibc_proto::ibc::lightclients::optimism::v1::ClientState as RawClientState;
use optimism_ibc_proto::ibc::lightclients::optimism::v1::ConsensusState as RawConsensusState;
use prost::Message;

const SYNC_COMMITTEE_SIZE: usize = PRESET.SYNC_COMMITTEE_SIZE;

#[derive(Default)]
struct MockClientReader {
    client_state: Option<ClientState>,
    consensus_state: BTreeMap<Height, ConsensusState>,
    time: Option<Time>,
}

impl HostContext for MockClientReader {
    fn host_timestamp(&self) -> Time {
        self.time.unwrap_or_else(Time::now)
    }
}

impl HostClientReader for MockClientReader {}

impl store::KVStore for MockClientReader {
    fn set(&mut self, _key: Vec<u8>, _value: Vec<u8>) {}

    fn get(&self, _key: &[u8]) -> Option<Vec<u8>> {
        None
    }

    fn remove(&mut self, _key: &[u8]) {}
}

impl ClientReader for MockClientReader {
    fn client_state(&self, client_id: &ClientId) -> Result<Any, light_client::Error> {
        let cs = self
            .client_state
            .clone()
            .ok_or_else(|| light_client::Error::client_state_not_found(client_id.clone()))?;
        Ok(Any::try_from(cs).unwrap())
    }

    fn consensus_state(
        &self,
        client_id: &ClientId,
        height: &Height,
    ) -> Result<Any, light_client::Error> {
        let state = self
            .consensus_state
            .get(height)
            .ok_or_else(|| {
                light_client::Error::consensus_state_not_found(client_id.clone(), *height)
            })?
            .clone();
        Ok(Any::try_from(state).unwrap())
    }
}

/// Reads `{ now, client_state, consensus_state }` (the latter two hex-encoded)
/// from a prover-generated `.json` fixture and returns the decoded bytes.
fn read_state_json(path: &str) -> (i64, Vec<u8>, Vec<u8>) {
    let json = std::fs::read(path).expect("json not found");
    let v: serde_json::Value = serde_json::from_slice(&json).unwrap();
    let now = v["now"].as_i64().unwrap();
    let raw_cs = hex::decode(v["client_state"].as_str().unwrap()).unwrap();
    let raw_cons_state = hex::decode(v["consensus_state"].as_str().unwrap()).unwrap();
    (now, raw_cs, raw_cons_state)
}

#[test]
fn test_update_client() {
    // Generated by optimism-ibc-relay-prover#prover_test.go#TestSetupHeadersForUpdateLatest
    let (now, raw_cs, raw_cons_state) = read_state_json("../testdata/update_client_header.json");
    run_update_client(now, raw_cs, raw_cons_state);
}

fn run_update_client(now: i64, raw_cs: Vec<u8>, raw_cons_state: Vec<u8>) {
    let client = OptimismLightClient::<SYNC_COMMITTEE_SIZE>;
    let raw_cs = RawClientState::decode(raw_cs.as_slice()).unwrap();
    let raw_cons_state = RawConsensusState::decode(raw_cons_state.as_slice()).unwrap();

    let cs = ClientState::try_from(raw_cs).unwrap();
    let cons_state = ConsensusState::try_from(raw_cons_state).unwrap();

    let mut cons_states = BTreeMap::new();
    cons_states.insert(cs.latest_height, cons_state);

    let client_message =
        std::fs::read("../testdata/update_client_header.bin").expect("file not found");
    let client_message = Any::try_from(client_message).unwrap();

    let ctx = MockClientReader {
        client_state: Some(cs),
        consensus_state: cons_states,
        time: Some(Time::from_unix_timestamp(now, 0).unwrap()),
    };

    let client_id = ClientId::from_str("optimism-1").unwrap();
    client
        .update_client(&ctx, client_id, client_message)
        .unwrap();
}

#[test]
fn test_submit_misbehaviour_success() {
    let client = OptimismLightClient::<SYNC_COMMITTEE_SIZE>;
    let (now, cs, cons_state, client_message) = get_misbehaviour_data();
    let mut cons_states = BTreeMap::new();
    cons_states.insert(cs.latest_height, cons_state.clone());

    let ctx = MockClientReader {
        client_state: Some(cs),
        consensus_state: cons_states,
        time: Some(Time::from_unix_timestamp(now, 0).unwrap()),
    };

    let client_id = ClientId::from_str("optimism-01").unwrap();
    let result = client
        .update_client(&ctx, client_id, client_message)
        .unwrap();
    match result {
        UpdateClientResult::Misbehaviour(data) => {
            let frozen = ClientState::try_from(data.new_any_client_state)
                .unwrap()
                .frozen;
            assert!(frozen, "Client should be frozen after misbehaviour");
        }
        _ => panic!("Expected success result"),
    }
}

#[test]
fn test_submit_misbehaviour_future_success() {
    let client = OptimismLightClient::<SYNC_COMMITTEE_SIZE>;
    let (now, cs, cons_state, client_message) = get_misbehaviour_future_data();
    let mut cons_states = BTreeMap::new();
    cons_states.insert(cs.latest_height, cons_state.clone());

    let ctx = MockClientReader {
        client_state: Some(cs),
        consensus_state: cons_states,
        time: Some(Time::from_unix_timestamp(now, 0).unwrap()),
    };

    let client_id = ClientId::from_str("optimism-01").unwrap();
    let result = client
        .update_client(&ctx, client_id, client_message)
        .unwrap();
    match result {
        UpdateClientResult::Misbehaviour(data) => {
            let frozen = ClientState::try_from(data.new_any_client_state)
                .unwrap()
                .frozen;
            assert!(frozen, "Client should be frozen after misbehaviour");
        }
        _ => panic!("Expected success result"),
    }
}

fn get_misbehaviour_data() -> (i64, ClientState, ConsensusState, Any) {
    // The test parameters are created by optimism-ibc-relay-prover#tools/misbehaviour/l2/past
    let (now, raw_cs, raw_cons_state) = read_state_json("../testdata/submit_misbehaviour.json");

    let raw_cs = RawClientState::decode(raw_cs.as_slice()).unwrap();
    let cs = to_misbehaviour_client_state(raw_cs);

    let raw_cons_state = RawConsensusState::decode(raw_cons_state.as_slice()).unwrap();
    let cons_state = ConsensusState::try_from(raw_cons_state).unwrap();

    let client_message =
        std::fs::read("../testdata/submit_misbehaviour.bin").expect("file not found");
    let client_message = Any::try_from(client_message).unwrap();

    (now, cs, cons_state, client_message)
}

fn get_misbehaviour_future_data() -> (i64, ClientState, ConsensusState, Any) {
    // The test parameters are created by optimism-ibc-relay-prover#tools/misbehaviour/l2/future
    let (now, raw_cs, raw_cons_state) =
        read_state_json("../testdata/submit_misbehaviour_future.json");

    let raw_cs = RawClientState::decode(raw_cs.as_slice()).unwrap();
    let cs = to_misbehaviour_client_state(raw_cs);

    let raw_cons_state = RawConsensusState::decode(raw_cons_state.as_slice()).unwrap();
    let cons_state = ConsensusState::try_from(raw_cons_state).unwrap();

    let client_message =
        std::fs::read("../testdata/submit_misbehaviour_future.bin").expect("file not found");
    let client_message = Any::try_from(client_message).unwrap();

    (now, cs, cons_state, client_message)
}

/// Builds a client state for the misbehaviour fixtures. `ClientState::try_from`
/// is used (instead of a struct literal) so the test only relies on the crate's
/// public API. The IBC fields are unused by these tests, so they are zeroed.
fn to_misbehaviour_client_state(mut raw_cs: RawClientState) -> ClientState {
    raw_cs
        .fault_dispute_game_config
        .as_mut()
        .unwrap()
        .status_defender_win = 0;
    raw_cs.frozen = false;
    raw_cs.ibc_store_address = vec![0u8; 20];
    raw_cs.ibc_commitments_slot = vec![0u8; 32];
    ClientState::try_from(raw_cs).unwrap()
}
