name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
      - name: Install components
        run: |
          rustup component add rustfmt clippy
          cargo install cargo-machete
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Check clippy
        run: cargo clippy --locked -- -D warnings
      - name: Check deps
        run: cargo machete
      - name: unit-test
        run: cargo test --release
