name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2025-01-01
          components: rustfmt, clippy
      - uses: actions-rs/cargo@v1
        name: format check
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        name: clippy check
        with:
          command: clippy
          args: -- -D warnings
      - uses: actions-rs/cargo@v1
        name: unit-test
        with:
          command: test
          args: --release
